# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Docker image and deploy to Azure Web App

env:
  AZURE_WEBAPP_NAME: KEYBOARDIFY-CLIENT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  create-envfile:
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      run: |
        touch .env 
        echo ENV_VITE_BACKEND_SERVER: ${{ secrets.BACKEND_SERVER }} >> .env
        echo ENV_VITE_DOMAIN: ${{ secrets.DOMAIN }} >> .env
        echo ENV_VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }} >> .env
        echo ENV_VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }} >> .env
        echo ENV_VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }} >> .env
        echo ENV_VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
        echo ENV_VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} >> .env
        echo ENV_VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }} >> .env
        echo ENV_VITE_STRIPE_KEY: ${{ secrets.STRIPE_KEY }} >> .env
        echo ENV_VITE_STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }} >> .env
        cat .env

  build:
    runs-on: ubuntu-latest
    needs: create-envfile

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
     - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'keyboardify-client'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BDE6CCD38F7847E893104ECC8CA6D835 }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
